apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.backend.service.name }}"
spec:
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: "{{ .Values.backend.deploy.name }}"
  type: "{{ .Values.backend.service.type }}"
