apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.frontend.service.name }}"
spec:
  ports:
    - port: 80
      targetPort: 3001
  selector:
    app: "{{ .Values.frontend.deploy.name }}"
  type: "{{ .Values.frontend.service.type }}"
